const SORT_ALPHABETICALLY = "SORT_ALPHABETICALLY";
const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
const GET_COUNTRIES = "GET_COUNTRIES";
const SORT_BY_POPULATION = "SORT_BY_POPULATION";
const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
const SET_TOTAL_PAGES = "SET_TOTAL_PAGES";

export {
  SORT_ALPHABETICALLY,
  FILTER_BY_CONTINENT,
  GET_COUNTRIES,
  SORT_BY_POPULATION,
  SET_CURRENT_PAGE,
  SET_TOTAL_PAGES,
};
